### ISSUE TITLE
Error: invalid method name 

### ISSUE THREAD

**Issue by Fatman13** [web3-protocol/web3curl-js#1]
Hello,

While trying out web3curl with this [asset](https://twitter.com/qc_qizhou/status/1742248089954713666), i am getting the following error...

<img src="https://github.com/web3-protocol/web3curl-js/assets/1591330/60ac19a9-3bc0-4690-bbf5-3d5b3d1ad57e" width="640">

Any ideas on how to fix it?

**Comment by qizhou** [comment]
Looks like chain 3333 is not yet supported.  Could you please try 

https://0x9bc02c1aa4f26ea4786558b1b312a2f0f9a74373.3333.w3link.io/tower.jpg

Meanwhile we will debug the issue in web3curl.

**Comment by qzhodl** [comment]
@nand2  FYI: The RPC of chainId 3333 is http://88.99.30.186:9545, and it is the devnet-2 of EthStorage

**Comment by nand2** [comment]
Yes indeed, the issue is that the embedded RPC definitions does not include devnet-2 of Ethstorage.
You can make it work with web3curl by adding a chain override : 

```
web3curl -c 3333=http://88.99.30.186:9545 "web3://0x9bc02c1aa4f26ea4786558b1b312a2f0f9a74373:3333/tower.jpg" --output /tmp/img.jpg
```

That being said, I agree that "invalid method name" is not an helpful error message, I need to catch it earlier. So I'll keep this issue open for now.

**Comment by nand2** [comment]
Oh, in fact there is a embedded definition for chain 3333, which is ``https://testnet.web3q.io:8545`` -- this comes from https://chainid.network/chains.json ( via https://github.com/ethereum-lists/chains ). I guess this is a previous version of the devnet (devnet-1 ?).
If this is a permanent change, maybe it would be good to submit a PR to update the RPC to https://github.com/ethereum-lists/chains, and/or update the DNS of testnet.web3q.io ?

**Comment by qzhodl** [comment]
> Oh, in fact there is a embedded definition for chain 3333, which is `https://testnet.web3q.io:8545` -- this comes from https://chainid.network/chains.json ( via https://github.com/ethereum-lists/chains ). I guess this is a previous version of the devnet (devnet-1 ?). If this is a permanent change, maybe it would be good to submit a PR to update the RPC to https://github.com/ethereum-lists/chains, and/or update the DNS of testnet.web3q.io ?

This should be not a permanent change, and I'm curious that web3curl -c 3333=http://88.99.30.186:9545 can overwrite the original mapping (3333= https://testnet.web3q.io:8545) right? 

The reason that I asked is that I got "web3curl: Error: ReadableStream is not defined" when running 'web3curl -c 3333=http://88.99.30.186:9545 "web3://0x9bc02c1aa4f26ea4786558b1b312a2f0f9a74373:3333/tower.jpg" --output /tmp/img.jpg' on my side

**Comment by qzhodl** [comment]
> > Oh, in fact there is a embedded definition for chain 3333, which is `https://testnet.web3q.io:8545` -- this comes from https://chainid.network/chains.json ( via https://github.com/ethereum-lists/chains ). I guess this is a previous version of the devnet (devnet-1 ?). If this is a permanent change, maybe it would be good to submit a PR to update the RPC to https://github.com/ethereum-lists/chains, and/or update the DNS of testnet.web3q.io ?
> 
> This should be not a permanent change, and I'm curious that web3curl -c 3333=http://88.99.30.186:9545 can overwrite the original mapping (3333= https://testnet.web3q.io:8545) right?
> 
> The reason that I asked is that I got "web3curl: Error: ReadableStream is not defined" when running 'web3curl -c 3333=http://88.99.30.186:9545 "web3://0x9bc02c1aa4f26ea4786558b1b312a2f0f9a74373:3333/tower.jpg" --output /tmp/img.jpg' on my side

oh, that's because I am using node 16, and after I switch to node 18, everything is OK

**Comment by nand2** [comment]
Ok I have updated web3protocol/curl so that we get more infos : 
```bash
$ web3curl "web3://0x9bc02c1aa4f26ea4786558b1b312a2f0f9a74373:3333/tower.jpg" -v
* Fetching URL web3://0x9bc02c1aa4f26ea4786558b1b312a2f0f9a74373:3333/tower.jpg
* Parsing URL ...
* Host domain name resolver: (none)
* Contract address: 0x9bc02c1aa4f26ea4786558b1b312a2f0f9a74373
* Contract chain id: 3333
* Configured RPCs for chain 3333 (fallback mode) : https://testnet.web3q.io:8545
*
* Resolve mode determination... 
> 0xdd473fae
< 0x
* Resolve mode: auto
*
* Path parsing... 
web3curl: Path parsing: Error: Invalid method name: tower.jpg
```
We now see the previous steps (donain name resolution, determined resolved mode), and the error message is a bit more clear.
We also see the RPCs configured for the chain.

Should be enough to understand the issues now :)
